title: RubyVE
name: RubyVE
tagline: Grupo de Usuarios Ruby de Venezuela

connect:
  twitter: https://twitter.com/rubyve
  gplus: https://plus.google.com/communities/106213524853304399957
  ggoogle: https://groups.google.com/forum/#!forum/rubyve
  github: https://github.com/ruby-ve
  irc: irc://irc.freenode.net/#rubyve
  temario: https://docs.google.com/spreadsheet/ccc?key=0AlFW4ZKapXzcdDlpLXk4QjdNaHlDSGh5cURSV1JtX3c&hl=en&forcehl=1#gid=1

analytics:
  google:
    id: UA-19430884-2
    domain: ruby.org.ve

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - CC-LICENSE
  - LAYON-LICENSE

markdown: redcarpet
highlighter: rouge

permalink: pretty

host: 0.0.0.0
port: 3000
baseurl: /
url: http://ruby.org.ve
lsi: false

gems:
  - jekyll-sitemap

prose:
  rooturl: '_posts'
  siteurl: 'https://ruby-ve.github.io/'
  media: 'assets'
  metadata:
    _posts:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'post'
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
          type: "text"
      - name: "author"
        field:
          element: "text"
          label: "Author Full Name"
          value: ""
          placeholder: "Pedro Perez"
          type: "text"
      - name: "author_twitter"
        field:
          element: "text"
          label: "Author Twitter Handle"
          value: ""
          placeholder: "rubyve"
          type: "text"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          value: ""
          placeholder: "Add a post description under 155 characters."
          type: "text"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
          options:
            - name: "Comunidad"
              value: "comunidad"
            - name: "Hangout"
              value: "hangout"
            - name: "Ruby Tuesdays"
              value: "ruby-tuesdays"
            - name: "Reunión"
              value: "reunión"
            - name: "Anuncio"
              value: "anuncio"
